export const actions = {
	UPDATE_TABLE_DATA: "UPDATE_TABLE_DATA",
	GET_SEASONS: "GET_SEASONS",
	UPDATE_PAGE: "UPDATE_PAGE",
	UPDATE_ROWS_PER_PAGE: "UPDATE_ROWS_PER_PAGE",
	SET_PAGE_TO_0: "SET_PAGE_TO_0",
};
